// Diverse deck-topic prompts for the landing typewriter — 105 real topics
// across 15 worlds (business, education, science/medicine, legal, nonprofit,
// religion, arts, personal, party, sports, food/travel, real-estate, HR,
// events), interleaved by world so the rotation always feels varied.
export const PROMPT_IDEAS = [
  "Help me build a seed-round pitch deck for my B2B logistics SaaS startup.",
  "Help my 5th grader make a science fair presentation about how volcanoes erupt.",
  "I need slides to defend my master's thesis on coral reef acoustics.",
  "Build my hackathon demo deck for an app that turns voice memos into to-do lists.",
  "Help me build the closing argument slides for my personal injury trial.",
  "I need our annual impact report deck for the clean water nonprofit.",
  "Help me build slides for my sermon series on the Book of Psalms.",
  "Help me build a pitch deck for my indie coming-of-age drama film.",
  "Make a wedding welcome slideshow telling our engagement story and timeline.",
  "I need a ridiculous PowerPoint night deck ranking every sandwich my roommates make.",
  "Build our game-week scouting report deck on next week's opponent.",
  "Help me build a two-week Japan itinerary deck for our family trip.",
  "Build an open house listing deck for the mid-century modern ranch I'm selling.",
  "Build our new hire onboarding deck covering benefits and company culture.",
  "Build my keynote deck for a design conference on the future of AI interfaces.",
  "I need a Series B fundraising deck for my AI developer-tools company.",
  "I need slides for my AP US History unit on the causes of the Civil War.",
  "Build a grand rounds deck presenting an unusual case of Lyme disease.",
  "I need a system design review deck for our microservices migration plan.",
  "I'm presenting to city council about our proposed bike lane expansion, need a deck.",
  "Build a grant proposal deck for our youth mentorship program.",
  "I'm teaching Hebrew school and need a lesson deck on the Passover story.",
  "I need an exhibition proposal deck on Ming Dynasty ceramics for the museum board.",
  "Help me build a memorial slideshow celebrating my grandmother's life.",
  "Build a PowerPoint night deck proving my cat is objectively the best pet.",
  "I need a 12-week strength program deck to hand my new personal training client.",
  "Build a menu and tasting-notes deck for our supper club dinner party.",
  "I need a luxury listing presentation deck for a downtown penthouse condo.",
  "Help me build the all-hands deck announcing our company reorg.",
  "Create a webinar deck on 5 growth marketing tactics to try in 2026.",
  "Put together our quarterly board update deck for the skincare brand.",
  "Make a kindergarten letter-of-the-week lesson deck for the letter B.",
  "Turn my research on CRISPR off-target effects into a poster session deck.",
  "Put together our sprint retrospective deck for the mobile app team.",
  "Turn my policy brief on affordable housing zoning reform into slides.",
  "Put together the fundraising gala deck for our food bank's holiday drive.",
  "Build a fundraising deck for our mosque's new prayer hall building fund.",
  "Build our band's pitch deck for record labels about our debut album.",
  "Build a where-are-they-now slideshow for our 20-year high school reunion.",
  "Make an unhinged PowerPoint arguing which Pixar movie has the saddest opening scene.",
  "Build a parent meeting deck covering our youth soccer team's spring schedule.",
  "Create a meal-prep and macros plan deck for my month of clean eating.",
  "Build our consulting engagement kickoff deck for the retail client's supply-chain overhaul.",
  "Build a calibration deck for engineering managers doing performance reviews.",
  "Build a trade show booth pitch deck for our robotics company.",
  "I need a go-to-market strategy deck for our EU market launch.",
  "Build my university lecture slides on the causes of the French Revolution.",
  "Prepare a tumor board case review deck for a rare pediatric sarcoma case.",
  "Create an all-hands deck announcing our new CI/CD pipeline rollout.",
  "Build a compliance training deck on GDPR data privacy requirements for staff.",
  "Create a volunteer orientation deck for new disaster relief volunteers.",
  "Create an orientation deck for our meditation retreat on mindfulness practices.",
  "Create a production design deck for our Shakespeare in the Park staging.",
  "Help me build my personal year-in-review deck to send to friends and family.",
  "Build our friend group's definitive ranking deck of every fast food chain's fries.",
  "Help me build a halftime adjustment deck breaking down the opponent's defense.",
  "Build a backpacking route deck for my summer trip across Southeast Asia.",
  "Create a financial planning deck laying out my client's retirement strategy.",
  "Create a diversity and inclusion training deck for our new managers.",
  "Help me prep a panel discussion deck on the future of remote work.",
  "Build me a 90-second demo day pitch deck for my fintech app.",
  "Help me make a book report presentation on To Kill a Mockingbird for class.",
  "Help me build slides for my undergrad research symposium talk on microplastics in lakes.",
  "Build a roadmap deck for our open-source JavaScript testing framework.",
  "I need an exhibit deck to accompany my congressional testimony on AI regulation.",
  "I need a campaign kickoff deck for our climate action coalition.",
  "Make a trivia and games deck for our youth group's lock-in night.",
  "Build a lookbook presentation deck for my fall fashion collection.",
  "Make a baby shower slideshow telling the parents-to-be's journey to this point.",
  "I need a PowerPoint night roast deck of the bride's dating history for her bachelorette.",
  "Build my personal training plan deck for my first marathon.",
  "Help me build a mood board deck for our kitchen remodel.",
  "Build an investment memo deck for our proposed strip mall acquisition.",
  "Build a deck announcing our updated remote work policy to the whole company.",
  "Build the awards ceremony program deck for our industry recognition gala.",
  "Turn our annual shareholder letter into a presentation deck.",
  "I'm running a teacher training workshop on differentiated instruction, need slides.",
  "I need an R&D update deck on our Phase II migraine drug trial results.",
  "I need an RFC proposal deck arguing we should switch database architectures.",
  "Build a lobbying deck advocating for paid family leave legislation.",
  "Build a town hall deck explaining our new affordable housing initiative to residents.",
  "Build a presentation for the interfaith council about our shared community garden project.",
  "Help me build a concept pitch deck for our new indie platformer game.",
  "Build a retirement tribute deck celebrating my coworker's 30 years at the company.",
  "Build a trash-talk slideshow for our office fantasy football draft day.",
  "Make a rules and draft order deck for our fantasy basketball league.",
  "Build a coffee shop crawl deck ranking the best espresso spots in the city.",
  "I'm hosting a home-buying 101 seminar for first-time buyers, need a deck.",
  "Help me build a launch deck for our new employee mental health benefits program.",
  "Create a breakout session deck on API best practices for our user conference.",
  "Create a competitive landscape teardown deck for our new project-management tool.",
  "Create a welcome deck for incoming freshmen at orientation week.",
  "Make me a lecture deck for astronomy club on how we detect exoplanets.",
  "Build a research briefing deck on our latest model alignment techniques.",
  "Help me build a deck that explains prior art to a jury in our patent case.",
  "Create a donor stewardship deck showing exactly where last year's donations went.",
  "I need slides for our HOA meeting explaining the new community rules.",
  "I'm running a Comic-Con fan panel ranking the best anime villains, need slides.",
  "Create a family reunion deck mapping our family tree across four generations.",
  "Make a joke conspiracy-theory deck arguing that birds aren't real for game night.",
  "Build a post-match VOD review deck for our esports team's tournament run.",
  "Make a wine country weekend itinerary deck for our friends' getaway.",
  "Build a due diligence summary deck for the company we're considering acquiring.",
  "Build an internal runbook deck documenting our incident response procedures.",
  "Build a silent auction item showcase deck for our charity gala after-party."
  ];
